### ISSUE TITLE
Il Percorso

### ISSUE THREAD

**Issue by gdemartino** [ondata/pompei2033#3]
Inserire le quattro foto: te le invio via mail

**Comment by nelsonmau** [comment]
@gdemartino non le ho ricevute

**Comment by gdemartino** [comment]
Foto da inserire:
SETTEMBRE 2013
Il progetto:
![il progetto 2](https://cloud.githubusercontent.com/assets/11832501/10262643/8a870df0-69d1-11e5-9204-5dddac6d2f90.png)
SETTEMBRE 2014
L'evento
![evento](https://cloud.githubusercontent.com/assets/11832501/10262648/d5169aa2-69d1-11e5-90b7-f3184a12bceb.jpg)
MAGGIO 2015
Il gruppo
![il gruppo](https://cloud.githubusercontent.com/assets/11832501/10262666/5f9b2daa-69d2-11e5-9347-723a615468f6.jpg)

SETTEMBRE 2015
Il festival
![il festival](https://cloud.githubusercontent.com/assets/11832501/10262659/f677e840-69d1-11e5-973e-684e4e1de5be.jpg)

**Comment by nelsonmau** [comment]
fatto
